apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: croa-operator-default-deny
spec:
  podSelector:
    matchLabels:
      clusterresourceoverride.operator: "true"
  policyTypes:
  - Ingress
  - Egress
