apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: croa-allow-egress-to-api-server
spec:
  egress:
  - ports:
    - port: 6443
      protocol: TCP
  podSelector:
    matchLabels:
      clusterresourceoverride: "true"
  policyTypes:
  - Egress
