apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: croa-default-deny
spec:
  podSelector:
    matchLabels:
      clusterresourceoverride: "true"
  policyTypes:
  - Ingress
  - Egress
