apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: croa-allow-ingress-to-webhook
spec:
  ingress:
  - ports:
    - port: 9400
      protocol: TCP
  podSelector:
    matchLabels:
      clusterresourceoverride: "true"
  policyTypes:
  - Ingress
